### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by RobGraham** [electrode-io/electrode-keepalive#8]
Team,

I wanted to inform you that since we introduced electrode into our code we noticed pretty drastic memory leaks which caused us to revert our changes. While preliminary review of the code doesn't show anything obvious, the evidence is clear.

![screen shot 2017-06-15 at 11 49 34 am](https://user-images.githubusercontent.com/1311204/27197019-961019bc-51c1-11e7-8619-62f3ac9cb802.png)

This graph shows our memory metrics of our UI application, which a partnered API also saw the same memory decline. No other code changes were introduced. You'll notice the flat line is a set of servers that don't have the module while the rapid decline includes electrode. 

Same is true for our regularly deployed development environment (flat lines are other non-prod environments)

![screen shot 2017-06-15 at 11 59 27 am](https://user-images.githubusercontent.com/1311204/27197188-2fad8b9a-51c2-11e7-9a3b-dc7724c85615.png)

We followed your implementation instructions completely. Since removing electrode, our memory is flat.

**Comment by jchip** [comment]
Hi, thanks for reporting this.  Since you filed it under this module only does that mean you added only this module?  Is it possible for you to show me the code snippet from your app that uses this module?  

Also, from the graph I am not very clear on the memory leak.  Do you see a memory usage in your app using electrode that trends up continuously?

**Comment by jchip** [comment]
ok, it's *available memory*.  I see.

**Comment by jchip** [comment]
this module by nature keeps connections and sockets alive, so the more there are the more memory will be used.  It doesn't actually implement the keep alive logic.  It just change the logic to lookup idle sockets for reused.  The actual implementation is from NodeJS's keep alive agent.

**Comment by jchip** [comment]
could you let me know what you use this module for?  we use it to keep connections to our internal servers alive so the server IPs remain mostly unchanged and it's just NodeJS keepalive agent that's managing sockets.  

I will do some testing to make sure idle sockets get freed.

**Comment by RobGraham** [comment]
This module was recommended because of the way you implement DNS caching. 
Originally we did want to keep sockets alive by passing `keepAlive: true`, but then we decided to let them get killed off automatically. This belief comes from your readme example. You're passing `keepAlive: true` which gets passed into the Agent constructor. Node's agent by default does NOT keep the sockets open so removing this option we believed was all that was necessary. Regardless of the option, we still saw memory issues. 

Our application in production gets about 30rps and makes 2 downstream calls per request. We believed that DNS resolution would be taken care of by the module while still opening a new socket then killing it on `end`

**Comment by RobGraham** [comment]
As far as how we were using it here's a dumb down version will private info removed:

```
const ElectrodeKeepAlive = require("electrode-keepalive");
const httpRequest = require("request-promise");

const keepAlive = new ElectrodeKeepAlive();

httpRequest({
    uri: ...,
    agent: keepAlive.agent
})
```

**Comment by jchip** [comment]
Thanks for the info.  I will look into them.  I will also double check our prod servers.  We are using this in a few thousand prod servers and so far I haven't received any reports on unusual memory usage.  

I do notice that our code doesn't clean up the DNS pre-fetch record though.

**Comment by jchip** [comment]
Were you using any kind of keep alive agent before?  This module doesn't add any functionality to the keep alive part.  It's just to alter how the keep alive code in NodeJS does idle socket lookup.  We need this because our data centers uses Global DNS to do DC balancing and failover, but if you don't have such need, you can just use the regular NodeJS http keep alive agent as is.  I wonder if you would have memory issue with that.
